spring.application.name=moodtracker

spring.datasource.url=jdbc:postgresql://localhost:5433/mood_tracker
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


jwt.secret=dGhpcyBpcyBhIHZlcnkgbG9uZyBzZWNyZXQga2V5IGZvciBtb29kdHJhY2tlciEhIQ==
jwt.expiration=86400000